### ISSUE TITLE
建议增加 cache.dll.json 文件路径配置

### ISSUE THREAD

**Issue by purocean** [fingerpan/vue-cli-plugin-dll#16]
这个插件方便了我们 dll 的配置。使用 dll 的目的之一是为了减少构建时间。我们会把不会变动的一些基础库放入 dll 中。会提前把 dll 打包好然后构建服务器执行构建。但是因为 `cache.dll.json` 文件路径写死再包目录下面，所以我们不能将这个文件纳入版本管理，服务器依然要执行一次 dll 构建。我有几个建议可以讨论一下 :)

1. 不再使用 `cache.dll.json` 文件，直接扫描 `output` 目录中的 `.dll.js` 文件
2. 自定义配置 `cache.dll.json` 路径

**Comment by fingerpan** [comment]
非常感谢你的建议，
目前这个问题正在规划中。
1.  打算采用output目录扫描机制，但是有可能将插件对output目录旧文件的删除没有成功，导致扫描出多余的文件会产生引用问题。
2. 自定义配置方案是一个可选的方案，考虑采纳。
建议先采用手动注入的方式进行注入，等待我这周末升级之后之后fix这个问题。

**Comment by fingerpan** [comment]
解决思路：
1. 增加扫描output目录，如果找不到catch文件，采用扫描机制进行自动注入js、css 文件。
2. 如果插件对旧的*.dll.js文件删除不成功，会提示风险。
3. 增加对catch.json文件的配置。
4. 增加支持在注入时加入版本号，构建时不加版本（可覆盖旧文件）（考虑）

**Comment by fingerpan** [comment]
我已经在v1.1.5版本增加自定义配置cache.dll.json路径。
