### ISSUE TITLE
ypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by yangcore** [fingerpan/vue-cli-plugin-dll#20]
config.plugin('copy').tap(args => {
                    args[0][0].ignore.push(dll.outputDir + '/**')
                    args[0].push({
                        from: dll.outputPath,
                        toType: 'dir',
                        ignore: ['*.js', '*.css', '*.manifest.json']
                    })
                    return args
                })

运行serve时报错，这个copy，可以给一个配置参数不，我的dll没有放在public下面

**Comment by mylhei** [comment]
@yangcore 怎么解决的？
