### ISSUE TITLE
多入口公共runtime的问题

### ISSUE THREAD

**Issue by hubo0831** [fingerpan/vue-cli-plugin-dll#23]
在vue-element-admin使用dll的配置，生成dll文件没发生错误 ，但生成build:prod时出错。
vue.config.js：
{
pluginOptions: {
        dll: {
            entry: {
                vuedll: ['vue', 'vuex', 'vue-router', 'axios'],
                elementui: ['element-ui']
            },
            output: path.resolve(__dirname, './public-dll'),
            cacheFilePath: path.resolve(__dirname, './public-dll'),
            open: true,
            inject: true
        }
    }
}
生成dll后：
![image](https://user-images.githubusercontent.com/10137315/56857951-c066e580-69a5-11e9-98f7-6769d5db3968.png)
生成build:prod报错：
ScriptExtHtmlWebpackPlugin: no asset with href 'jsruntime.723ebb37.dll.js'
我觉得可能是两个dll之间的公共代码没有处理好

**Comment by fingerpan** [comment]
@hubo0831 我新建了项目，并且用了你的配置。但是我并不会有生成runtime.dll.js。这个是怎么生成的呢？

**Comment by hubo0831** [comment]
vue-element-admin请参考：https://github.com/PanJiaChen/vue-element-admin
如果配置一样，则可能是使用的依赖不一致；

**Comment by hubo0831** [comment]
我的项目：https://github.com/hubo0831/vue-element-admin
依赖更新了，与原项目不一样，请参见yarn.lock

**Comment by fingerpan** [comment]
@hubo0831 已经定位问题，在新包1.1.7解决这个问题。升级一下包就可以了。
