### ISSUE TITLE
Entry of 'vuetify/lib' crashes the dll build

### ISSUE THREAD

**Issue by Arsync** [fingerpan/vue-cli-plugin-dll#24]
Additional line in service.js

```log('Starting build dll...')
return new Promise((resolve, reject) => {
	webpack(webpackConfig, (err, stats) => {
		if (err) {
			return reject(err)
		} else if (stats.hasErrors()) {

			// This one:
			console.log(stats.compilation.errors[0]);

			return reject(new Error('Build failed with errors.'))
		}
		log('Build complete.')
		resolve()
	})
})
```

gives me following:

`Starting build dll...
ModuleBuildError: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[MODULE_TYPE] is not a function`

It builds only when I comment entry of 'vuetify/lib'.

**Comment by fingerpan** [comment]
Thank you for your feedback. I have solved this problem.
