### ISSUE TITLE
如何不使用vue-cli-plugin-dll?

### ISSUE THREAD

**Issue by xiangnanscu** [fingerpan/vue-cli-plugin-dll#27]
你好, 我试用了vue-cli-plugin-dll之后, 准备看看不使用它的build时间变化, 我把vue.config.js里面相关代码全部删除了, 但是我build的时候发现仍然有dll.js输出...如何解决这个问题呢?

**Comment by fingerpan** [comment]
只要确认参数open为false就可以了
