### ISSUE TITLE
能否增加一些Webpack-Plugin的支持？

### ISSUE THREAD

**Issue by windylaugit** [fingerpan/vue-cli-plugin-dll#38]
因项目需求，webpack打包时使用了一些插件：
IgnorePlugin - 用于过滤moment的语言包
BundleAnalyzerPlugin - 项目依赖分析
UglifyJsPlugin - 打包构建优化
WebpackBar - 打包进度UI
。。。
等等
是否 Dll 可以提供一种方式能使用一些filter之外的Webpack的plugin，以支持在使用dll的前提下，能完成特定的打包目的？

**Comment by fingerpan** [comment]
构建dll文件和构建主入口的配置相对有不同，在vue-cli-plugin-dll项目中是直接利用了主文件的配置，但是在代码中只允许了部分插件，避免有些插件影响到dll的构建。但是也会让这个webpack构建配置变得单一，无法满足楼主所需要自定义打包目的。
可以考虑支持一下自定义的plugin配置，感谢反馈建议。
核心问题应该是避免dll的插件配置污染到主配置。

**Comment by windylaugit** [comment]
> 构建dll文件和构建主入口的配置相对有不同，在vue-cli-plugin-dll项目中是直接利用了主文件的配置，但是在代码中只允许了部分插件，避免有些插件影响到dll的构建。但是也会让这个webpack构建配置变得单一，无法满足楼主所需要自定义打包目的。
> 可以考虑支持一下自定义的plugin配置，感谢反馈建议。
> 核心问题应该是避免dll的插件配置污染到主配置。

Thanks for reply!
-----
目前暂时放弃特殊打包，类似问题均采用其他方案处理 - CDN + externals
